name: Test Homebrew Formula

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Formula/**'

jobs:
  test-formula:
    name: Test Formula
    runs-on: macos-latest

    steps:
      - name: Checkout Homebrew Tap Repo
        uses: actions/checkout@v4

      - name: Find Modified Formulas
        id: find_formula
        run: |
          # Find which formula was modified
          FORMULA_CHANGED=$(git diff --name-only origin/main | grep 'Formula/' || echo "")
          echo "FORMULA_CHANGED=$FORMULA_CHANGED" >> $GITHUB_ENV

      - name: Brew Install and Test
        if: env.FORMULA_CHANGED != ''
        run: |
          FORMULA_FILE="./${FORMULA_CHANGED}"
          echo "Testing formula: $FORMULA_FILE"
          brew install --build-from-source "$FORMULA_FILE"
          brew test "$FORMULA_FILE"