name: Test Formula Locally

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Formula/**/*.rb'

jobs:
  test-formula:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: so we can compare to base branch

      - name: Find modified formula files
        id: find-formula
        run: |
          FORMULA_CHANGED=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '^Formula/.*\.rb' || echo "")
          echo "FORMULA_CHANGED=$FORMULA_CHANGED" >> $GITHUB_ENV

      - name: Output modified formula
        if: env.FORMULA_CHANGED != ''
        run: |
          echo "Modified formula: $FORMULA_CHANGED"

      - name: Install and Test modified formula
        if: env.FORMULA_CHANGED != ''
        env:
          HOMEBREW_NO_INSTALL_FROM_API: 1  # Ensures it uses the local Formula, not Homebrew/core
        run: |
          brew install --build-from-source "./${{ env.FORMULA_CHANGED }}"
          brew test "./${{ env.FORMULA_CHANGED }}"