name: Test Formula Locally

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Formula/**'

jobs:
  test-formula:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history so we can diff against origin/main

      - name: Fetch main branch
        run: |
          git fetch origin main

      - name: Find which formula was modified
        id: find-formula
        run: |
          FORMULA_CHANGED=$(git diff --name-only origin/main | grep '^Formula/' || echo "")
          echo "FORMULA_CHANGED=$FORMULA_CHANGED" >> $GITHUB_ENV

      - name: Set formula path
        if: env.FORMULA_CHANGED != ''
        run: |
          echo "Detected modified formula: $FORMULA_CHANGED"

      - name: Install and Test formula
        if: env.FORMULA_CHANGED != ''
        env:
          HOMEBREW_NO_INSTALL_FROM_API: 1  # Force using the formula file locally, not the Brew API
        run: |
          brew install --build-from-source "./${{ env.FORMULA_CHANGED }}"
          brew test "./${{ env.FORMULA_CHANGED }}"