name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Release version tag (example: v3.1.0-preview.2 or v3.0.2)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  
jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Version Info
        id: parse
        run: |
          TAG="${{ inputs.version_tag }}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          VERSION=${TAG#v}  # remove leading "v"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          if [[ "$VERSION" == *"preview"* ]]; then
            FORMULA="dsc-cli-preview.rb"
            FORMULA_NAME="dsc-cli-preview"
          else
            FORMULA="dsc-cli.rb"
            FORMULA_NAME="dsc-cli"
          fi
          echo "FORMULA=${FORMULA}" >> $GITHUB_ENV
          echo "FORMULA_NAME=${FORMULA_NAME}" >> $GITHUB_ENV

      - name: Download and calculate SHAs
        id: download
        run: |
          BASE_URL="https://github.com/PowerShell/DSC/releases/download/${TAG}"
          ARM_FILE="DSC-${VERSION}-aarch64-apple-darwin.tar.gz"
          X86_FILE="DSC-${VERSION}-x86_64-apple-darwin.tar.gz"

          curl -L -o arm.tar.gz "${BASE_URL}/${ARM_FILE}"
          curl -L -o x86.tar.gz "${BASE_URL}/${X86_FILE}"

          ARM_SHA=$(sha256sum arm.tar.gz | awk '{print $1}')
          X86_SHA=$(sha256sum x86.tar.gz | awk '{print $1}')

          echo "ARM_SHA=${ARM_SHA}" >> $GITHUB_ENV
          echo "X86_SHA=${X86_SHA}" >> $GITHUB_ENV

      - name: Clean up downloaded files
        run: |
            rm -f ./arm.tar.gz
            rm -f ./x86.tar.gz

      - name: Update Formula
        run: |
            FORMULA_PATH="Formula/${FORMULA}"

            # Update version
            sed -i "s|version \".*\"|version \"${VERSION}\"|" $FORMULA_PATH

            # Update ARM URL and SHA
            sed -i "s|url \".*-aarch64-apple-darwin.tar.gz\"|url \"https://github.com/PowerShell/DSC/releases/download/${TAG}/DSC-${VERSION}-aarch64-apple-darwin.tar.gz\"|" $FORMULA_PATH
            sed -i "/aarch64-apple-darwin.tar.gz/{n;s|sha256 \".*\"|sha256 \"${ARM_SHA}\"|}" $FORMULA_PATH

            # Update x86_64 URL and SHA
            sed -i "s|url \".*-x86_64-apple-darwin.tar.gz\"|url \"https://github.com/PowerShell/DSC/releases/download/${TAG}/DSC-${VERSION}-x86_64-apple-darwin.tar.gz\"|" $FORMULA_PATH
            sed -i "/x86_64-apple-darwin.tar.gz/{n;s|sha256 \".*\"|sha256 \"${X86_SHA}\"|}" $FORMULA_PATH

      - name: Create Branch and PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update ${{ env.FORMULA_NAME }} to ${{ env.VERSION }}"
          branch: update-${{ env.FORMULA_NAME }}-${{ env.VERSION }}
          title: "Update ${{ env.FORMULA_NAME }} to ${{ env.VERSION }}"
          body: |
            This PR updates the `${{ env.FORMULA_NAME }}` formula to version `${{ env.VERSION }}`.
          labels: |
            automated-pr
          base: main