name: Update DSC Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to update (e.g., v3.0.2, v3.1.0-preview.3)"
        required: true

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          if [[ "${{ github.event.inputs.tag }}" == *-preview* ]]; then
            echo "FORMULA=dsc-cli-preview.rb" >> $GITHUB_ENV
          else
            echo "FORMULA=dsc-cli.rb" >> $GITHUB_ENV
          fi
          echo "VERSION=$(echo '${{ github.event.inputs.tag }}' | sed 's/^v//')" >> $GITHUB_ENV

      - name: Download Release Assets
        run: |
          mkdir -p tmp
          curl -L -o tmp/arm.tar.gz https://github.com/PowerShell/DSC/releases/download/${TAG}/DSC-${VERSION}-aarch64-apple-darwin.tar.gz
          curl -L -o tmp/x86.tar.gz https://github.com/PowerShell/DSC/releases/download/${TAG}/DSC-${VERSION}-x86_64-apple-darwin.tar.gz

      - name: Generate SHA256 hashes
        id: sha
        run: |
          echo "ARM_SHA=$(shasum -a 256 tmp/arm.tar.gz | awk '{print $1}')" >> $GITHUB_ENV
          echo "X86_SHA=$(shasum -a 256 tmp/x86.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          FORMULA_PATH="Formula/${FORMULA}"

          sed -i.bak -e "s|^\(\s*version \).*|\1\"${VERSION}\"|" "$FORMULA_PATH"

          # Update ARM URL and SHA
          sed -i.bak -e "/if Hardware::CPU.arm?/ {
            N
            s|url \".*\"|url \"https://github.com/PowerShell/DSC/releases/download/${TAG}/DSC-${VERSION}-aarch64-apple-darwin.tar.gz\"|
            s|sha256 \".*\"|sha256 \"${ARM_SHA}\"|
          }" "$FORMULA_PATH"

          # Update x86 URL and SHA
          sed -i.bak -e "/else/ {
            N
            s|url \".*\"|url \"https://github.com/PowerShell/DSC/releases/download/${TAG}/DSC-${VERSION}-x86_64-apple-darwin.tar.gz\"|
            s|sha256 \".*\"|sha256 \"${X86_SHA}\"|
          }" "$FORMULA_PATH"

          rm "$FORMULA_PATH.bak"

      - name: Test Formula Locally
        run: |
          brew install --build-from-source ./Formula/${FORMULA}
          brew test ./Formula/${FORMULA}

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/${FORMULA}
          git commit -m "Update ${FORMULA} for release ${TAG}"
          git push